# Generated by Django 5.2.9 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
